from modules.peter import PeterWindow
from modules.ComboColor import ComboColor
from modules.selectFolder import SelectFolder
from modules.ComboRating import ComboRating
from modules.FindButton import FindButton
from modules.EnterButton import EnterButton
from modules.Rename import RenameButton
from modules.Separator import Separator
from modules.FromDigit import FromDigit
from modules.TextEdit import TextEdit
from modules.rename_example import RenameExample
from modules.OpenButton import OpenButton
from modules.change_dir import ChangeDir
from modules.CopyMoveButton import CopyMoveButton